### ISSUE TITLE
[1pt] Create basic structure for Rockets - Setup

### ISSUE THREAD

**Issue by killy10o10** [killy10o10/space-travelers-capstone#21]
- Create a route and a view component. Use `<NavLink />` for the page navigation links and style active class to indicate which section/page the user is currently on (underline active navigation link).
- Create a directory for all Redux state slice files.

**Comment by Haadiiii** [comment]
https://github.com/killy10o10/space-travelers-capstone/pull/27

**Comment by killy10o10** [comment]
https://github.com/killy10o10/space-travelers-capstone/pull/28
